### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by tomzi** [axllent/silverstripe-list-to-bootstrap-grid#1]
**Hello** axllent,

Is there a way to combine the list with the paginatedList so i can display a pagination at the end of my boostrap list  ?
That would be great.

Thank you for your help,
Thomas

**Comment by axllent** [comment]
Hi!

I don't see why you can't just use PaginatedList with the existing code "as-is"?

```php
<?php

class CategoryPage_Controller extends Controller
{
    public function getProductRows()
    {
        $rows = new ListToBootstrapGrid(
            $this->Products(),
            $columns = 3,
            $center = true
        );

       return new PaginatedList($rows, $this->getRequest());
    }
}
```

Does that not work for you? The rest (templating of the bootstrap grid) remains exactly the same, unless of course you wish to add page numbers etc.

I hope this helps, but please confirm?

Cheers,
Ralph

**Comment by tomzi** [comment]
Hi,

I did exactly what you show in your example but i wondered how to display page numbers, that would be awesome to have both bootstrap grid and pagination.
Did you already do this ?

Thank you for your answer.

Cheers,
Thomas

**Comment by axllent** [comment]
Hi Thomas,

There is no need to have pagination as part of the module as data you need is already returned in the above example (`getProductRows()`). It is very easy to add pagination to your page - Using the above example, your template would look something like:

```html
<!-- Begin product grid -->
<% loop $ProductRows %>
    <div class="row">
        <% loop $Items %>
            <div class="col-sm-{$Up.Width}<% if $First && $Up.Offset %> col-sm-offset-{$Up.Offset}<% end_if %>">
                <h2>$Title</h2>
                ...
            </div>
        <% end_loop %>
    </div>
<% end_loop %>
<!-- End product grid -->

<!-- Begin pagination pages -->
<% if $ProductRows.MoreThanOnePage %>
  <div class="pagination">
    <% if $ProductRows.NotFirstPage %>
        <a class="prev" href="$ProductRows.PrevLink">Prev</a>
    <% end_if %>
    <% loop $ProductRows.Pages %>
        <% if $CurrentBool %>
            $PageNum
        <% else %>
            <% if $Link %>
                <a href="$Link">$PageNum</a>
            <% else %>
                ...
            <% end_if %>
        <% end_if %>
        <% end_loop %>
    <% if $ProductRows.NotLastPage %>
        <a class="next" href="$ProductRows.NextLink">Next</a>
    <% end_if %>
  </div>
<% end_if %>
<!-- End pagination pages -->
```

Obviously you can style/change this to suit your own needs. Hope this helps?

Cheers,
Ralph

**Comment by tomzi** [comment]
Ralph,

Actually the pagination showed up but all my items are on the same page, even if i set a limit.
I think that won't work because if dump a paginated list without Boostrap, the list object is an ArrayList that owns all the items 
`    ["list":protected]=>
object(ArrayList)#118 (8) {
    ["items":protected]=>
    array(11) {
      [0]=>
      object(Commercial)#169 (17) {
        ["destroyed"]=>
        bool(false)
        ["model":protected]=>
        object(DataModel)#168 (1) {
          ["customDataLists":protected]=>
          array(0) {
          }
        }
        ...`
But if i add your list, the list object still contains all the items but splitted in as many arrays as rows and each arrays contains items so i got something like 
`["list":protected]=>
  object(ListToBootstrapGrid)#406 (10) {
    ["items":protected]=>
    array(4) {
      [0]=>
      object(ArrayData)#412 (8) {
        ["array":protected]=>
        array(3) {
          ["Width"]=>
          int(4)
          ["Offset"]=>
          int(0)
          ["Items"]=>
          object(ArrayList)#411 (8) {
            ["items":protected]=>
            array(3) {
            ...`

I don't know how to fix the problem yet, do you have a solution ?

Thanks!
Thomas

**Comment by axllent** [comment]
Hi Thomas,

The limit (`->setPageLength(<x>)`) wouldn't be for the number of items in total, but rather the number of rows that are returned by `ListToBootstrapGrid`.

So let's say you have 20 products, you were using `ListToBootstrapGrid` to create rows of 3 products, and you set your pagination to (`->setPageLength(3)`), then that would show you 3 rows of 3 products (ie: 9 products per page).

Does that help?

Cheers,
Ralph

**Comment by axllent** [comment]
I used this today and I can confirm that it works exactly as I explained above. I haven't had any response to my [previous message](https://github.com/axllent/silverstripe-list-to-bootstrap-grid/issues/1#issuecomment-293752678) so I am going to assume you got it working and I'm marking this as closed.
